# Generated by Django 3.1 on 2020-09-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'компанія', 'verbose_name_plural': 'компанії'},
        ),
    ]
