# Generated by Django 3.1.2 on 2021-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва компанії')),
                ('carrier_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('carrier_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ/ДРФО')),
                ('carrier_tax', models.CharField(blank=True, max_length=12, null=True, verbose_name='ІПН')),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва компанії')),
                ('consignee_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('consignee_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ/ДРФО')),
                ('consignee_tax', models.CharField(blank=True, max_length=12, null=True, verbose_name='ІПН')),
            ],
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва компанії')),
                ('consignor_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
                ('consignor_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ/ДРФО')),
                ('consignor_tax', models.CharField(blank=True, max_length=12, null=True, verbose_name='ІПН')),
            ],
        ),
        migrations.CreateModel(
            name='CustomsRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='код режиму')),
                ('regime_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='код транспорту')),
                ('vehicle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
        ),
    ]
