# Generated by Django 3.1.2 on 2021-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'перевізник', 'verbose_name_plural': 'перевізники'},
        ),
        migrations.AlterModelOptions(
            name='consignee',
            options={'verbose_name': 'одержувач', 'verbose_name_plural': 'одержувачі'},
        ),
        migrations.AlterModelOptions(
            name='consignor',
            options={'verbose_name': 'відправник', 'verbose_name_plural': 'відправники'},
        ),
        migrations.AlterModelOptions(
            name='customsregime',
            options={'verbose_name': 'митний режим', 'verbose_name_plural': 'митні режими'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'вид транспорту', 'verbose_name_plural': 'види транспорту'},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='тип транспорту'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='vehicle_type_code',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='код типу'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='код транспорту'),
        ),
    ]
