# Generated by Django 3.1.2 on 2021-01-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_forwarder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='код')),
                ('currency_letter', models.CharField(blank=True, max_length=3, null=True, verbose_name='літерний код')),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюти',
            },
        ),
    ]
