# Generated by Django 3.1.2 on 2021-01-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='код підрозділу')),
                ('office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'митний підрозділ',
                'verbose_name_plural': 'митні підрозділи',
            },
        ),
    ]
