# Generated by Django 3.1.2 on 2021-01-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_auto_20210117_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='код')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='найменування')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документи',
            },
        ),
    ]
