# Generated by Django 3.1.2 on 2021-01-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_auto_20210117_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='тип'),
        ),
    ]
