# Generated by Django 3.1.2 on 2021-01-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0012_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='номер заявки')),
                ('order_date', models.DateField(verbose_name='дата формування')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ПІБ водія')),
                ('driver_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='контактний телефон')),
                ('vehicle_number', models.TextField(verbose_name='номер ТЗ')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to='reference.carrier', verbose_name='перевізник')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='reference.consignee', verbose_name='одержувач')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='reference.consignor', verbose_name='відправник')),
                ('customs_departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='reference.customsoffice', verbose_name='митниця відправлення')),
                ('customs_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='reference.customsoffice', verbose_name='митниця призначення')),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarder', to='reference.forwarder', verbose_name='експедитор')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regime', to='reference.customsregime', verbose_name='митний режим')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='reference.vehicletype', verbose_name='тип транспорту')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='номер')),
                ('document_date', models.DateField(verbose_name='дата')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='reference.document', verbose_name='вид')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_document', to='order.order')),
            ],
            options={
                'verbose_name': 'документ до заявки',
                'verbose_name_plural': 'документи до заявки',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='найменування товару')),
                ('cargo_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='код УКТЗЕД')),
                ('cargo_weight', models.FloatField(blank=True, max_length=255, null=True, verbose_name='вага товару, кг')),
                ('cargo_addnumber', models.FloatField(blank=True, max_length=255, null=True, verbose_name='додаткові одиниці')),
                ('cargo_value', models.FloatField(blank=True, max_length=255, null=True, verbose_name='фактурна вартість')),
                ('cargo_value_uah', models.FloatField(blank=True, max_length=255, null=True, verbose_name='вартість, грн')),
                ('cargo_duties', models.FloatField(blank=True, max_length=255, null=True, verbose_name='митні платежі, грн')),
                ('cargo_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='reference.currency', verbose_name='валюта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='order.order')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товари',
            },
        ),
    ]
