# Generated by Django 3.1.2 on 2021-01-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210119_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер ТЗ'),
        ),
    ]
